version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Banking@Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./sql-scripts:/docker-entrypoint-initdb.d

  banking-api:
    build: .
    depends_on:
      - db
    environment:
      ConnectionStrings__BankingDb: "Server=db;Database=BankingDb;User=sa;Password=Banking@Pass123;"
    ports:
      - "5000:80"

volumes:
  sql_data: